---
# hosts could have been "remote" or "all" as well
- hosts:  localhost
  connection:  local
  become:  yes
  become_user:  root
  vars:
   - docroot:  /var/www/serversforhackers.com/public
  tasks:
   - name:  Add Nginx Repo
     apt_repository:
       repo:  ppa:nginx/stable
       state:  present
     register:  ppastable

   - name: Install Nginx
     apt:
       pkg:  nginx
       state: latest
       update_cache: yes
     when: ppastable|SUCCESS
     notify:
      - Start Nginx

   - name:  Create Web Root
     file:
      path:  '{{ docroot }}'
      mode:  775
      state: directory
      owner:  www-data
      group:  www-data
     notify:
      - Reload Nginx

  handlers:
     - name:  Start Nginx
       service:
         name:  nginx
         state:  started

     - name:  Reload Nginx
       service:
         name:  nginx
         state:  reloaded
